### ISSUE TITLE
[FEATURE REQUEST] Compatibility 11

### ISSUE THREAD

**Issue by DavidBruchmann** [WapplerSystems/t3-tag#2]
For v11 only the definition of checkbox items in the TCA has to be adjusted, as far as I see.
It's certainly possible to use the same branch / version for TYPO3 v11 and v12, with minor tweak.

**Comment by DavidBruchmann** [comment]
it's slightly more work to get it running in v11. a new branch for it would be probably better than making one branch working for both TYPO3 versions.

- checkboxes had to get an older configuration
- startime and endtime had to get an older configuration

**Comment by svewap** [comment]
Yes, I too would prefer a new branch

**Comment by DavidBruchmann** [comment]
see https://github.com/DavidBruchmann/t3-tag/tree/release/v11.
I'm unsure against which branch to file a PR
